const GAME_CONFIG = {
    STICK_GROWTH_SPEED: 5,
    STICK_FALL_SPEED: 0.05,
    STICK_WIDTH: 3,
    PLAYER_WIDTH: 20,
    PLAYER_HEIGHT: 30,
    PLATFORM_GAP_MULTIPLIER: 0.2,
    PLATFORM_WIDTH_MULTIPLIER: 0.15,
    GROUND_HEIGHT_MULTIPLIER: 0.7,
    PLAYER_WALK_SPEED: 4,
    LEG_ANIMATION_SPEED: 0.15,
    HEAD_RADIUS: 8,
    PLAYER_FALL_SPEED: 8,
    PLAYER_ROTATION_SPEED: 0.15,
};

const GAME_SOUNDS = {
    FALL: new Audio('data:audio/wav;base64,//uQRAAAAWMSLwUIYAAsYkXgoQwAEaYLWfkWgAI0wWs/ItAAAGDgYtAgAyN+QWaAAihwMWm4G8QQRDiMcCBcH3Cc+CDv/7xA4Tvh9Rz/y8QADBwMWgQAZG/ILNAARQ4GLTcDeIIIhxGOBAuD7hOfBB3/94gcJ3w+o5/5eIAIAAAVwWgQAVQ2ORaIQwEMAJiDg95G4nQL7mQVWI6GwRcfsZAcsKkJvxgxEjzFUgfHoSQ9Qq7KNwqHwuB13MA4a1q/DmBrHgPcmjiGoh//EwC5nGPEmS4RcfkVKOhJf+WOgoxJclFz3kgn//dBA+ya1GhurNn8zb//9NNutNuhz31f////9vt///z+IdAEAAAK4LQIAKobHItEIYCGAExBwe8jcToF9zIKrEdDYIuP2MgOWFSE34wYiR5iqQPj0JIeoVdlG4VD4XA67mAcNa1fhzA1jwHuTRxDUQ//iYBczjHiTJcIuPyKlHQkv/LHQUYkuSi57yQT//uggfZNajQ3Vmz+Zt//+mm3Wm3Q576v////+32///5/EOgAAADVghQAAAAA=='),
    SCREAM: new Audio('https://assets.mixkit.co/active_storage/sfx/2759/2759-preview.mp3'),
};